import type { PlayerRow } from "./types";

/** Mock player records across existing mock tables. */
export const mockPlayers: PlayerRow[] = [
  {
    id: "p1",
    alias: "RiverKing",
    tableId: "1",
    tableName: "High Stakes",
    handsPlayed: 342,
    suspiciousScore: 85,
    isFlagged: true,
    lastActive: "2026-07-22T14:30:00Z",
  },
  {
    id: "p2",
    alias: "BluffMaster",
    tableId: "1",
    tableName: "High Stakes",
    handsPlayed: 189,
    suspiciousScore: 12,
    isFlagged: false,
    lastActive: "2026-07-22T13:15:00Z",
  },
  {
    id: "p3",
    alias: "LuckyDog",
    tableId: "2",
    tableName: "Night Owls",
    handsPlayed: 456,
    suspiciousScore: 5,
    isFlagged: false,
    lastActive: "2026-07-23T05:45:00Z",
  },
  {
    id: "p4",
    alias: "AceHole",
    tableId: "2",
    tableName: "Night Owls",
    handsPlayed: 278,
    suspiciousScore: 45,
    isFlagged: false,
    lastActive: "2026-07-23T04:30:00Z",
  },
  {
    id: "p5",
    alias: "OmahaShark",
    tableId: "3",
    tableName: "Omaha Beach",
    handsPlayed: 512,
    suspiciousScore: 92,
    isFlagged: true,
    lastActive: "2026-07-23T06:15:00Z",
  },
  {
    id: "p6",
    alias: "FoldMachine",
    tableId: "3",
    tableName: "Omaha Beach",
    handsPlayed: 67,
    suspiciousScore: 38,
    isFlagged: false,
    lastActive: "2026-07-22T20:00:00Z",
  },
  {
    id: "p7",
    alias: "Chatterbox",
    tableId: "5",
    tableName: "The River",
    handsPlayed: 23,
    suspiciousScore: 8,
    isFlagged: true,
    lastActive: "2026-07-20T11:00:00Z",
  },
  {
    id: "p8",
    alias: "SilentPro",
    tableId: "5",
    tableName: "The River",
    handsPlayed: 891,
    suspiciousScore: 15,
    isFlagged: false,
    lastActive: "2026-07-23T06:30:00Z",
  },
  {
    id: "p9",
    alias: "QuickClick",
    tableId: "6",
    tableName: "Lowball",
    handsPlayed: 156,
    suspiciousScore: 78,
    isFlagged: true,
    lastActive: "2026-07-23T03:45:00Z",
  },
  {
    id: "p10",
    alias: "CallMeMaybe",
    tableId: "6",
    tableName: "Lowball",
    handsPlayed: 203,
    suspiciousScore: 55,
    isFlagged: false,
    lastActive: "2026-07-22T23:10:00Z",
  },
  {
    id: "p11",
    alias: "Grinder42",
    tableId: "2",
    tableName: "Night Owls",
    handsPlayed: 734,
    suspiciousScore: 3,
    isFlagged: false,
    lastActive: "2026-07-21T18:00:00Z",
  },
  {
    id: "p12",
    alias: "NoobNoob",
    tableId: "5",
    tableName: "The River",
    handsPlayed: 12,
    suspiciousScore: 0,
    isFlagged: false,
    lastActive: "2026-07-19T09:30:00Z",
  },
];
