import type { TableRow } from "./types";

export const mockTables: TableRow[] = [
  {
    id: "1",
    name: "High Stakes",
    gameType: "texas-holdem",
    stakes: "10/20",
    status: "active",
    handsPlayed: 1542,
    playerCount: 6,
    flaggedPlayerCount: 1,
  },
  {
    id: "2",
    name: "Night Owls",
    gameType: "texas-holdem",
    stakes: "2/5",
    status: "active",
    handsPlayed: 823,
    playerCount: 8,
    flaggedPlayerCount: 2,
  },
  {
    id: "3",
    name: "Omaha Beach",
    gameType: "omaha",
    stakes: "1/2",
    status: "active",
    handsPlayed: 412,
    playerCount: 5,
    flaggedPlayerCount: 0,
  },
  {
    id: "4",
    name: "Stud Farm",
    gameType: "stud",
    stakes: "5/10",
    status: "inactive",
    handsPlayed: 2091,
    playerCount: 0,
    flaggedPlayerCount: 0,
  },
  {
    id: "5",
    name: "The River",
    gameType: "texas-holdem",
    stakes: "1/2",
    status: "active",
    handsPlayed: 367,
    playerCount: 9,
    flaggedPlayerCount: 3,
  },
  {
    id: "6",
    name: "Lowball",
    gameType: "omaha",
    stakes: "0.5/1",
    status: "active",
    handsPlayed: 89,
    playerCount: 4,
    flaggedPlayerCount: 0,
  },
  {
    id: "7",
    name: "Closed for Maintenance",
    gameType: "texas-holdem",
    stakes: "2/5",
    status: "inactive",
    handsPlayed: 0,
    playerCount: 0,
    flaggedPlayerCount: 0,
  },
];
